inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

build:
    nodes:
        php7.4:
            environment:
                php:
                    version: 7.4
            analysis:
                tests:
                    override:
                        - php-scrutinizer-run
