inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

analysis:
    tests:
        override:
            - php-scrutinizer-run

build:
    nodes:
        php74:
            environment:
                php:
                    version: 7.4
        php80:
            environment:
                php:
                    version: 8.0

