inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

build:
    nodes:
        php74:
            environment:
                php: 7.4
        php80:
            environment:
                php: 8.0
