inherit: true

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

build:
    environment:
        php:
            version: 7.4
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
